server:
  port: ${PORT:8083}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nurairbnbc
    username: postgres
    password: Estudiar1995

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /
